---
- name: Ensure Git is installed
  yum:
    name: git
    state: present

- name: Clone YOLO repo from GitHub
  git:
    repo: "https://github.com/lembathomas/yolo.git"
    dest: /opt/yolo
    version: main
    force: yes

- name: Build backend Docker image
  community.docker.docker_image:
    build:
      path: /opt/yolo/backend
    name: lembadev/thomas-yolo-backend
    tag: v1.0.0

- name: Run backend container
  community.docker.docker_container:
    name: thomas-yolo-backend
    image: lembadev/thomas-yolo-backend:v1.0.0
    restart_policy: always
    depends_on:
      - mongo
    env:
      NODE_ENV: production
      MONGODB_URI: "mongodb://tom:1vh9Mdryh9KvkH7W@mongo:27017/yolomy?authSource=admin"
    ports:
      - "5000:5000"
