- name: Pull Backend image from Docker Hub
  community.docker.docker_image:
    name: "{{ backend_image }}"
    source: pull

- name: Run Backend container
  community.docker.docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ backend_port }}:5000"
    env:
      NODE_ENV: production
      MONGODB_URI: "mongodb://{{ mongo_root_user }}:{{ mongo_root_password }}@{{ mongo_container_name }}:27017/yolomy?authSource=admin"

- name: Wait for backend to be up
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ backend_port }}"
    delay: 5
    timeout: 120
