- name: Run MongoDB container
  community.docker.docker_container:
    name: mongo
    image: mongo:6.0
    state: started
    restart_policy: always
    ports:
      - "8000:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: tom
      MONGO_INITDB_ROOT_PASSWORD: 1vh9Mdryh9KvkH7W


  
