# roles/mongo/tasks/main.yaml

- name: Ensure Docker is installed
  ansible.builtin.package:
    name: docker.io
    state: present
  become: true

- name: Pull Mongo image from Docker Hub
  community.docker.docker_image:
    name: "{{ mongo_image }}"
    source: pull
  become: true

- name: Run Mongo container
  community.docker.docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ mongo_port }}:27017"
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ mongo_root_user }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_root_password }}"
  become: true
