---
- name: Build frontend Docker image
  community.docker.docker_image:
    build:
      path: /opt/yolo/client
    name: lembadev/thomas-yolo-client
    tag: v1.0.0

- name: Run frontend container
  community.docker.docker_container:
    name: thomas-yolo-client
    image: lembadev/thomas-yolo-client:v1.0.0
    restart_policy: always
    depends_on:
      - thomas-yolo-backend
    ports:
      - "3000:80"
